### ISSUE TITLE
Exception when attempting to place torch on side of furnace via right click

### ISSUE THREAD

**Issue by GrumpyChunks** [WalterWeight/RightClickTorch#1]
The following exception was thrown when torches were in the hotbar. Not a problem, if they're in the normal inventory, almost certain caused by bad assumptions made in the method [sanitiseTorchSlotIndex()](https://github.com/WalterWeight/RightClickTorch/blob/master/main/java/org/walterweight/rightclicktorch/RightClickTorch.java#L67)

```
---- Minecraft Crash Report ----
// I'm sorry, Dave.

Time: 24/06/15 23:38
Description: Unexpected error

java.lang.IndexOutOfBoundsException: Index: 44, Size: 39
    at java.util.ArrayList.rangeCheck(ArrayList.java:653)
    at java.util.ArrayList.get(ArrayList.java:429)
    at net.minecraft.inventory.Container.func_75139_a(SourceFile:104)
    at net.minecraft.inventory.Container.func_75141_a(SourceFile:385)
    at net.minecraft.client.network.NetHandlerPlayClient.func_147266_a(NetHandlerPlayClient.java:1027)
    at net.minecraft.network.play.server.S2FPacketSetSlot.func_148833_a(SourceFile:27)
    at net.minecraft.network.play.server.S2FPacketSetSlot.func_148833_a(SourceFile:10)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
    at java.util.ArrayList.rangeCheck(ArrayList.java:653)
    at java.util.ArrayList.get(ArrayList.java:429)
    at net.minecraft.inventory.Container.func_75139_a(SourceFile:104)
    at net.minecraft.inventory.Container.func_75141_a(SourceFile:385)
    at net.minecraft.client.network.NetHandlerPlayClient.func_147266_a(NetHandlerPlayClient.java:1027)
    at net.minecraft.network.play.server.S2FPacketSetSlot.func_148833_a(SourceFile:27)
    at net.minecraft.network.play.server.S2FPacketSetSlot.func_148833_a(SourceFile:10)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityClientPlayerMP['WalterWeight'/326, l='MpServer', x=144.61, y=64.62, z=-12.73]]
    Chunk stats: MultiplayerChunkCache: 623, 623
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (190,64,13), Chunk: (at 14,4,13 in 11,0; contains blocks 176,0,0 to 191,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 13022 game time, 13022 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 102 total; [EntitySkeleton['Skeleton'/1816, l='MpServer', x=129.50, y=47.00, z=11.50], EntitySkeleton['Skeleton'/545, l='MpServer', x=37.39, y=-30.62, z=25.73], EntitySkeleton['Skeleton'/1845, l='MpServer', x=71.50, y=30.00, z=5.50], EntityCreeper['Creeper'/1848, l='MpServer', x=110.50, y=17.00, z=-20.50], EntityZombieDog['entity.GraveStone.GSZombieDog.name'/69, l='MpServer', x=59.50, y=26.00, z=-4.50], EntityBat['Bat'/70, l='MpServer', x=63.60, y=26.02, z=-6.06], EntityBat['Bat'/71, l='MpServer', x=75.75, y=20.30, z=-2.15], EntityBat['Bat'/72, l='MpServer', x=68.75, y=40.02, z=25.35], EntityClientPlayerMP['WalterWeight'/326, l='MpServer', x=144.61, y=64.62, z=-12.73], EntityChicken['Chicken'/87, l='MpServer', x=67.44, y=73.00, z=-37.47], EntityChicken['Chicken'/89, l='MpServer', x=75.53, y=70.00, z=28.47], EntityChicken['Chicken'/91, l='MpServer', x=73.13, y=62.40, z=47.38], EntitySheep['Sheep'/93, l='MpServer', x=69.19, y=64.00, z=41.56], EntitySkeleton['Skeleton'/105, l='MpServer', x=89.50, y=22.00, z=-89.91], EntityEnderman['Enderman'/106, l='MpServer', x=91.13, y=17.00, z=-79.50], EntityZombie['Zombie'/107, l='MpServer', x=88.50, y=19.00, z=30.50], EntityCreeper['Creeper'/108, l='MpServer', x=89.50, y=19.00, z=32.50], EntityChicken['Chicken'/109, l='MpServer', x=80.59, y=65.00, z=52.41], EntitySkeleton['Skeleton'/118, l='MpServer', x=112.00, y=42.00, z=-80.59], EntitySkeleton['Skeleton'/119, l='MpServer', x=105.50, y=13.00, z=-68.50], EntitySpider['Spider'/120, l='MpServer', x=107.59, y=13.00, z=-72.75], EntitySkeleton['Skeleton'/121, l='MpServer', x=103.50, y=20.00, z=-52.16], EntitySkeleton['Skeleton'/122, l='MpServer', x=98.50, y=20.00, z=-54.50], EntityChicken['Chicken'/123, l='MpServer', x=114.53, y=78.00, z=-36.53], EntitySkeleton['Skeleton'/129, l='MpServer', x=127.72, y=48.00, z=-85.16], EntityCreeper['Creeper'/130, l='MpServer', x=112.25, y=41.00, z=-78.06], EntityZombie['Zombie'/131, l='MpServer', x=112.50, y=22.00, z=-58.50], EntityItem['item.item.egg'/132, l='MpServer', x=120.34, y=76.13, z=-43.13], EntityChicken['Chicken'/133, l='MpServer', x=131.66, y=67.00, z=-33.47], EntitySkeleton['Skeleton'/134, l='MpServer', x=115.50, y=46.00, z=-12.09], EntityBat['Bat'/135, l='MpServer', x=117.75, y=38.10, z=-20.47], EntityBat['Bat'/136, l='MpServer', x=126.99, y=42.00, z=-21.53], EntitySkeleton['Skeleton'/137, l='MpServer', x=112.50, y=39.00, z=-27.50], EntitySkeleton['Skeleton'/138, l='MpServer', x=125.34, y=46.00, z=12.78], EntityCreeper['Creeper'/139, l='MpServer', x=118.50, y=47.00, z=16.50], EntitySkeleton['Skeleton'/140, l='MpServer', x=119.47, y=50.00, z=32.97], EntityCreeper['Creeper'/152, l='MpServer', x=142.50, y=21.00, z=-88.50], EntityZombie['Zombie'/153, l='MpServer', x=140.50, y=47.00, z=-84.06], EntityZombie['Zombie'/154, l='MpServer', x=130.16, y=48.00, z=-83.63], EntityCreeper['Creeper'/155, l='MpServer', x=131.78, y=47.00, z=-88.13], EntityCreeper['Creeper'/156, l='MpServer', x=141.50, y=46.00, z=-80.50], EntitySkeleton['Skeleton'/157, l='MpServer', x=131.50, y=41.00, z=-14.91], EntitySkeleton['Skeleton'/158, l='MpServer', x=143.50, y=38.00, z=46.50], EntitySkeleton['Skeleton'/159, l='MpServer', x=133.91, y=39.00, z=45.53], EntityZombie['Zombie'/160, l='MpServer', x=137.53, y=38.00, z=52.03], EntityCreeper['Creeper'/1958, l='MpServer', x=124.50, y=81.00, z=-69.50], EntityChicken['Chicken'/168, l='MpServer', x=150.63, y=73.00, z=-67.44], EntityChicken['Chicken'/169, l='MpServer', x=155.16, y=70.00, z=-69.50], EntityChicken['Chicken'/170, l='MpServer', x=146.63, y=71.00, z=-75.59], EntityCreeper['Creeper'/1962, l='MpServer', x=138.50, y=37.00, z=57.50], EntityChicken['Chicken'/171, l='MpServer', x=156.16, y=70.00, z=-69.53], EntityCreeper['Creeper'/1963, l='MpServer', x=139.50, y=37.00, z=58.50], EntityItem['item.item.egg'/172, l='MpServer', x=154.13, y=72.13, z=-66.41], EntityCreeper['Creeper'/1964, l='MpServer', x=138.50, y=37.00, z=59.50], EntityItem['item.item.egg'/174, l='MpServer', x=156.88, y=70.13, z=-69.13], EntitySkeleton['Skeleton'/175, l='MpServer', x=156.50, y=23.00, z=-32.50], EntityCreeper['Creeper'/176, l='MpServer', x=156.34, y=14.00, z=-36.09], EntityZombie['Zombie'/177, l='MpServer', x=158.50, y=23.00, z=-27.50], EntityZombie['Zombie'/178, l='MpServer', x=160.03, y=24.00, z=-36.50], EntitySkeleton['Skeleton'/179, l='MpServer', x=158.50, y=23.00, z=-30.50], EntityEnderman['Enderman'/180, l='MpServer', x=152.63, y=27.00, z=20.06], EntitySpider['Spider'/202, l='MpServer', x=164.38, y=25.00, z=-66.56], EntityBat['Bat'/204, l='MpServer', x=163.75, y=24.29, z=-42.25], EntityCow['Cow'/205, l='MpServer', x=168.06, y=63.00, z=-52.31], EntityCow['Cow'/206, l='MpServer', x=171.38, y=63.00, z=-52.28], EntityCow['Cow'/207, l='MpServer', x=167.47, y=63.00, z=-50.47], EntityCow['Cow'/208, l='MpServer', x=170.91, y=63.00, z=-53.97], EntityEnderman['Enderman'/209, l='MpServer', x=171.72, y=29.00, z=-40.44], EntityZombie['Zombie'/210, l='MpServer', x=171.50, y=51.00, z=-44.34], EntityZombie['Zombie'/211, l='MpServer', x=171.34, y=51.00, z=-45.22], EntitySkeleton['Skeleton'/212, l='MpServer', x=180.53, y=48.00, z=-50.91], EntityZombie['Zombie'/213, l='MpServer', x=173.31, y=53.00, z=-37.69], EntitySkeleton['Skeleton'/215, l='MpServer', x=174.66, y=50.00, z=-36.75], EntityCreeper['Creeper'/216, l='MpServer', x=165.84, y=15.00, z=-19.69], EntityZombie['Zombie'/217, l='MpServer', x=160.50, y=23.00, z=-24.50], EntityZombie['Zombie'/218, l='MpServer', x=171.75, y=55.00, z=-31.97], EntityBat['Bat'/1754, l='MpServer', x=91.53, y=17.00, z=-79.44], EntitySkeleton['Skeleton'/219, l='MpServer', x=164.50, y=32.00, z=-11.50], EntitySkeleton['Skeleton'/220, l='MpServer', x=169.50, y=32.00, z=-10.50], EntityBat['Bat'/1756, l='MpServer', x=92.66, y=20.10, z=-84.06], EntitySkeleton['Skeleton'/225, l='MpServer', x=189.50, y=27.00, z=-40.50], EntitySkeleton['Skeleton'/226, l='MpServer', x=186.94, y=41.00, z=-32.53], EntityZombie['Zombie'/228, l='MpServer', x=186.16, y=20.00, z=-19.78], EntityZombie['Zombie'/229, l='MpServer', x=197.34, y=40.00, z=-23.09], EntityZombie['Zombie'/230, l='MpServer', x=187.50, y=44.00, z=-22.50], EntityZombie['Zombie'/231, l='MpServer', x=174.50, y=49.73, z=-30.69], EntitySquid['Squid'/233, l='MpServer', x=179.38, y=48.34, z=35.28], EntitySquid['Squid'/234, l='MpServer', x=181.47, y=44.75, z=34.03], EntitySquid['Squid'/235, l='MpServer', x=184.03, y=49.16, z=37.22], EntitySquid['Squid'/236, l='MpServer', x=186.63, y=48.72, z=38.63], EntitySquid['Squid'/237, l='MpServer', x=189.38, y=49.38, z=37.31], EntitySquid['Squid'/239, l='MpServer', x=196.78, y=56.19, z=52.69], EntityBat['Bat'/240, l='MpServer', x=206.81, y=17.34, z=-84.21], EntityZombie['Zombie'/241, l='MpServer', x=187.94, y=43.00, z=-23.44], EntityBat['Bat'/242, l='MpServer', x=192.63, y=43.00, z=-17.96], EntitySpider['Spider'/244, l='MpServer', x=201.56, y=46.00, z=17.66], EntityBat['Bat'/245, l='MpServer', x=202.03, y=46.49, z=44.36], EntitySquid['Squid'/247, l='MpServer', x=197.50, y=56.00, z=49.50], EntitySquid['Squid'/250, l='MpServer', x=196.59, y=58.31, z=49.94], EntityBat['Bat'/252, l='MpServer', x=209.52, y=18.45, z=-68.45], EntitySkeleton['Skeleton'/253, l='MpServer', x=217.50, y=49.00, z=0.50], EntityBat['Bat'/254, l='MpServer', x=199.75, y=13.10, z=64.53]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 8.1 (amd64) version 6.3
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 177024456 bytes (168 MB) / 1499987968 bytes (1430 MB) up to 3817865216 bytes (3641 MB)
    JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1472 48 mods loaded, 48 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
    UCHIJAAAA   FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1472-1.7.10.jar) 
    UCHIJAAAA   Forge{10.13.4.1472} [Minecraft Forge] (forge-1.7.10-10.13.4.1472-1.7.10.jar) 
    UCHIJAAAA   Aroma1997Core{1.0.2.13} [Aroma1997Core] (Aroma1997Core-1.7.10-1.0.2.13.jar) 
    UCHIJAAAA   CodeChickenCore{1.0.6.43} [CodeChicken Core] (minecraft.jar) 
    UCHIJAAAA   InfiniBows{1.3.0 build 20} [InfiniBows] (minecraft.jar) 
    UCHIJAAAA   NotEnoughItems{1.0.4.107} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.107-universal.jar) 
    UCHIJAAAA   VeinMiner_coremod{0.27.1_build.unknown} [Core mod] (minecraft.jar) 
    UCHIJAAAA   <CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
    UCHIJAAAA   bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) 
    UCHIJAAAA   Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4.jar) 
    UCHIJAAAA   deconstruction{2.2.5} [The Deconstruction Mod] ([MC1.7.10]deconstruction[v2.2.5].jar) 
    UCHIJAAAA   Aroma1997CoreHelper{1.0.2.13} [Aroma1997Core|Helper] (Aroma1997Core-1.7.10-1.0.2.13.jar) 
    UCHIJAAAA   AromaBackup{0.0.0.5} [AromaBackup] (AromaBackup-1.7.10-0.0.0.5.jar) 
    UCHIJAAAA   Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
    UCHIJAAAA   ChickenChunks{1.3.4.19} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.19-universal.jar) 
    UCHIJAAAA   chisel{2.3.10.37} [Chisel 2] (Chisel2-2.3.10.37.jar) 
    UCHIJAAAA   CoFHCore{1.7.10R3.0.2} [CoFH Core] (CoFHCore-[1.7.10]3.0.2-262.jar) 
    UCHIJAAAA   EasyCrafting{1.7.10-2.0.1.16} [Easy Crafting] (EasyCrafting-1.7.10-2.0.1.16.jar) 
    UCHIJAAAA   endercompass{1.1} [Ender Compass] (EnderCompass-1.7.10-1.1.jar) 
    UCHIJAAAA   fognerf{1.7.10-0.3} [Fog Nerf] (fognerf-1.7.10-0.4.jar) 
    UCHIJAAAA   GraveStone{2.12.3} [GraveStone] (GraveStone-2.12.4.jar) 
    UCHIJAAAA   inpure|core{1.7.10R1.0.0B9} [INpureCore] (INpureCore-[1.7.10]1.0.0B9-62.jar) 
    UCHIJAAAA   inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) 
    UCHIJAAAA   IronChest{6.0.60.741} [Iron Chest] (ironchest-1.7.10-6.0.60.741-universal.jar) 
    UCHIJAAAA   jacb{1.0.2} [JACB] (JACB-1.7.10-1.0.2.jar) 
    UCHIJAAAA   journeymap{5.0.1} [JourneyMap] (JourneyMap5.0.1_Unlimited_MC1.7.10.jar) 
    UCHIJAAAA   JourneyMapServer{1.0.5_MC1.7.10} [JourneyMapServer] (JourneyMapServer1.0.5_MC1.7.10.jar) 
    UCHIJAAAA   malisiscore{1.7.10-0.12.3} [MalisisCore] (malisiscore-1.7.10-0.12.3.jar) 
    UCHIJAAAA   malisisdoors{1.7.10-1.8.2} [Malisis' Doors] (malisisdoors-1.7.10-1.8.2.jar) 
    UCHIJAAAA   NEIAddons{1.12.10.33} [NEI Addons] (neiaddons-1.12.10.33-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|AppEng{1.12.10.33} [NEI Addons: Applied Energistics 2] (neiaddons-1.12.10.33-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|Botany{1.12.10.33} [NEI Addons: Botany] (neiaddons-1.12.10.33-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|Forestry{1.12.10.33} [NEI Addons: Forestry] (neiaddons-1.12.10.33-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|CraftingTables{1.12.10.33} [NEI Addons: Crafting Tables] (neiaddons-1.12.10.33-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|ExNihilo{1.12.10.33} [NEI Addons: Ex Nihilo] (neiaddons-1.12.10.33-mc1.7.10.jar) 
    UCHIJAAAA   neiintegration{1.0.9} [NEI Integration] (NEIIntegration-MC1.7.10-1.0.9.jar) 
    UCHIJAAAA   ThermalFoundation{1.7.10R1.0.0} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.0.0-81.jar) 
    UCHIJAAAA   ThermalExpansion{1.7.10R4.0.1} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.1-182.jar) 
    UCHIJAAAA   RedstoneArsenal{1.7.10R1.1.0} [Redstone Arsenal] (RedstoneArsenal-[1.7.10]1.1.0-80.jar) 
    UCHIJAAAA   RightClickTorch{1.0} [RightClickTorch] (RightClickTorch-1.0.jar) 
    UCHIJAAAA   runicdungeons{1.1.5} [Runic Dungeons] (runicdungeons-1.1.5.jar) 
    UCHIJAAAA   SolarExpansion{1.6a} [Solar Expansion] (SolarExpansion-Basic-1.6a.jar) 
    UCHIJAAAA   ThermalDynamics{1.7.10R1.0.0} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.0.0-122.jar) 
    UCHIJAAAA   VeinMiner{0.27.1_build.unknown} [Vein Miner] (VeinMiner-1.7.10_0.27.1.unknown.jar) 
    UCHIJAAAA   VeinMinerModSupport{0.27.1_build.unknown} [Mod Support] (VeinMiner-1.7.10_0.27.1.unknown.jar) 
    UCHIJAAAA   Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
    UCHIJAAAA   Ztones{1.7.10} [Ztones] (Ztones-1.7.10-2.2.1.jar) 
    GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 350.12' Renderer: 'GeForce GTX 780/PCIe/SSE2'
    CoFHCore: -[1.7.10]3.0.2-262
    ThermalFoundation: -[1.7.10]1.0.0-81
    ThermalExpansion: -[1.7.10]4.0.1-182
    RedstoneArsenal: -[1.7.10]1.1.0-80
    ThermalDynamics: -[1.7.10]1.0.0-122
    Launched Version: forge-10.13.4.1472
    LWJGL: 2.9.1
    OpenGL: GeForce GTX 780/PCIe/SSE2 GL version 4.5.0 NVIDIA 350.12, NVIDIA Corporation
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Resource Packs: []
    Current Language: English (US)
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Anisotropic Filtering: Off (1)
```

**Comment by GrumpyChunks** [comment]
Fixed via https://github.com/WalterWeight/RightClickTorch/commit/320ef1728b7fb521f1a86140577f478104dcbba4
